#!/bin/bash
#PBS -N myjob
#PBS -q workq
#PBS -l nodes=node4+node5
#PBS -j oe
cd $PBS_O_WORKDIR
cat $PBS_NODEFILE > pbs_nodes
NPROCS=`wc -l < $PBS_NODEFILE`
NNODES=`uniq $PBS_NODEFILE | wc -l`

#cd /home/sarthak/hellotest
#export omp_threads=8

#export OMP_PROC_BIND=true
#export OMP_PLACES=cores

#echo `uniq $PBS_NODEFILE` | tr ' ' '\n' > unique_nodes

/apps/software/openmpi/bin/mpirun --hostfile $PBS_NODEFILE --map-by ppr:1:socket:pe=1 ./main.out
#./hello_cuda
